name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some other tasks
        run: echo {{ github }}

        

      - name: Create Check Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'name=A Mighty Test' \
            -f 'head_sha=${{ github.event.pull_request.head.sha }}' \
            -f 'status=in_progress' \
            -f 'output[title]=A Mighty Summary' \
            /repos/${{ github.repository }}/check-runs

        
