name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create Check Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'name=job2' \
            -f 'head_sha=${{ github.event.workflow_run.pull_requests[0].head.sha }}' \
            -f 'status=in_progress' \
            -f 'output[title]=A Mighty Summary' \
            -f "output[summary]=" \
            /repos/${{ github.repository }}/check-runs


      - name: Processing        
        run: sleep 10


      - name: Complete Check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs/job2 \
            --input - <<- EOF
            {
              "conclusion": "success",
              "output": {
                "title": "My Check Run Title 🚀",
                "summary": "**Summary**: The run completed.",
                "text": "Everything worked as expected. You should see a logo above."
               }
            }
          EOF 

        
