name: Workflow 2

on:
  status

jobs:
  job2:
    runs-on: ubuntu-latest
    if: >- 
      github.event.state == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create Check Run
        id: checkrun
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'name=job2' \
            -f 'head_sha=${{ github.event.workflow_run.pull_requests[0].head.sha }}' \
            -f 'status=in_progress' \
            -f 'output[title]=A Mighty Summary' \
            -f "output[summary]=" \
            --jq '.id' \
            /repos/${{ github.repository }}/check-runs)
 
            echo "checkId=$CHECKID" >> $GITHUB_OUTPUT          

      - name: Write GitHub context to log
        env:
          GITHUB_LOG: ${{ toJSON(steps) }}
        run: echo "$GITHUB_LOG"

      - name: Complete Check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs/${{ steps.checkrun.outputs.checkId }} \
            -f name="job2" -f "status=completed" -f conclusion=success 
            

        
